---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 5.1.2
  - name: community.general
    version: 10.5.0
  - name: community.sops
    version: 2.0.3
  - name: kubernetes.core
    version: 5.2.0
  - name: ansible.controller
    version: 4.6.8 #for 2.5
  - name: ansible.platform
    version: 2.5.20250213
  - name: ansible.hub
  - name: infra.controller_configuration
    version: 3.0.2
  - name: infra.aap_utilities
    version: 2.6.1
  - name: community.vmware
  - name: redhat.satellite
    version: 5.3.0
