---
collections:
  - name: community.general
    version: ">=6.0.0"
  - name: community.mysql
    version: ">=3.5.0"
  - name: community.libvirt
    version: ">=1.3.0"
  - name: ansible.utils
    version: ">=2.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: ngine_io.cloudstack
    version: ">=2.3.0"
  - name: community.sops
  - name: kubernetes.core
  - name: onepassword.connect
