---
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: community.general
  - name: community.sops
  - name: kubernetes.core
  - name: ansible.controller
  - name: ansible.platform
  - name: ansible.hub
  - name: infra.controller_configuration
  - name: infra.aap_utilities
  - name: community.vmware
  - name: redhat.satellite
  - name: community.docker
roles:
  - name: geerlingguy.docker
    version: 7.4.7
