#!/usr/bin/env python3
"""
List and configure NVIDIA GPUs for VFIO passthrough.

This script:
1. Detects NVIDIA GPUs and their associated audio devices
2. Gets their PCI vendor:device IDs
3. Configures /etc/modprobe.d/vfio.conf with the correct IDs
"""

import subprocess
import re
import os
import sys


def run_command(cmd):
    """Run a shell command and return output."""
    try:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, check=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error running command: {cmd}")
        print(f"Error: {e.stderr}")
        return ""


def get_nvidia_devices():
    """Get all NVIDIA PCI devices (GPUs and audio)."""
    devices = []
    
    # List all NVIDIA devices
    output = run_command("lspci -nn | grep -i nvidia")
    if not output:
        print("No NVIDIA devices found.")
        return devices
    
    for line in output.split('\n'):
        if not line:
            continue
            
        # Parse lspci output: "41:00.0 VGA compatible controller [0300]: NVIDIA Corporation Device [10de:2684] (rev a1)"
        match = re.match(r'^([0-9a-f:\.]+)\s+(.+)\[([0-9a-f]{4}):([0-9a-f]{4})\]', line, re.IGNORECASE)
        if match:
            pci_addr = match.group(1)
            description = match.group(2).strip()
            vendor_id = match.group(3)
            device_id = match.group(4)
            
            devices.append({
                'pci_addr': pci_addr,
                'description': description,
                'vendor_id': vendor_id,
                'device_id': device_id,
                'vfio_id': f"{vendor_id}:{device_id}"
            })
    
    return devices


def get_iommu_groups(devices):
    """Get IOMMU group for each device."""
    for device in devices:
        pci_addr = device['pci_addr']
        # Find IOMMU group
        iommu_path = f"/sys/bus/pci/devices/0000:{pci_addr}/iommu_group"
        if os.path.exists(iommu_path):
            group = os.path.basename(os.readlink(iommu_path))
            device['iommu_group'] = group
        else:
            device['iommu_group'] = 'N/A'
    
    return devices


def configure_vfio(devices):
    """Configure VFIO to bind to NVIDIA devices."""
    if not devices:
        print("No devices to configure.")
        return False
    
    # Get unique vendor:device IDs
    vfio_ids = list(set(d['vfio_id'] for d in devices))
    
    # Create modprobe configuration
    vfio_conf = f"""# VFIO configuration for NVIDIA GPU passthrough
# Auto-generated by list_and_configure_gpus.py
options vfio-pci ids={','.join(vfio_ids)}
softdep nvidia pre: vfio-pci
softdep nvidia_drm pre: vfio-pci
softdep nvidia_modeset pre: vfio-pci
softdep nouveau pre: vfio-pci
"""
    
    conf_path = "/etc/modprobe.d/vfio.conf"
    
    try:
        with open(conf_path, 'w') as f:
            f.write(vfio_conf)
        print(f"Written VFIO configuration to {conf_path}")
        return True
    except PermissionError:
        print(f"Permission denied writing to {conf_path}")
        print("Run this script as root.")
        return False
    except Exception as e:
        print(f"Error writing configuration: {e}")
        return False


def main():
    print("=" * 60)
    print("NVIDIA GPU VFIO Configuration")
    print("=" * 60)
    print()
    
    # Check if running as root
    if os.geteuid() != 0:
        print("Warning: Not running as root. Configuration may fail.")
        print()
    
    # Detect NVIDIA devices
    print("Detecting NVIDIA devices...")
    devices = get_nvidia_devices()
    
    if not devices:
        print("No NVIDIA devices found. Exiting.")
        sys.exit(0)
    
    # Get IOMMU groups
    devices = get_iommu_groups(devices)
    
    # Display devices
    print(f"\nFound {len(devices)} NVIDIA device(s):\n")
    for i, dev in enumerate(devices, 1):
        print(f"  {i}. {dev['pci_addr']} - {dev['description']}")
        print(f"     Vendor:Device ID: {dev['vfio_id']}")
        print(f"     IOMMU Group: {dev['iommu_group']}")
        print()
    
    # Configure VFIO
    print("Configuring VFIO...")
    if configure_vfio(devices):
        print("\nConfiguration complete!")
        print("\nVFIO IDs configured:")
        for dev in devices:
            print(f"  - {dev['vfio_id']} ({dev['description']})")
        print("\nNote: Reboot required for changes to take effect.")
    else:
        print("\nConfiguration failed!")
        sys.exit(1)


if __name__ == "__main__":
    main()

